learning_logs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/',include('users.urls', namespace='users')),
    url(r'', include('learning_logs_v1.urls', namespace='learning_logs_v1')),
]

learning_logs_v1/urls.py
#  定义learning_logs_v1的URL模式

from django.conf.urls import url
from . import views
# 这里对应的是learning_logs\urls中的namespaces
app_name = 'learning_logs_v1'
urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    url(r'^topics/', views.topics, name='topics'),
    url(r'^topic_id/(?P<topic_id>\d+)/$', views.topic_id, name='topic_id'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url(r'^delete_entry/$', views.delete_entry, name='delete_entry'),
]

users/urls.py
# 为应用程序users定义url模式

from django.conf.urls import url
from django.contrib.auth.views import login
from . import views
app_name = 'users'
urlpatterns = [
    # 登陆界面
    url(r'^login/$',login, {'template_name':'users/login.html'}, name='login'),
    # 退出
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册界面
    url(r'^register/$',views.register,name='register'),
]

learning_logs_v1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    #  用户学习的主题
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        # 返回模型字符串标识
        return self.text

class Entry(models.Model):
    #  学到的有关某个主题的具体知识
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        # 返回模型的字符串表示
        # 显示前五十个字
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs_v1/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        # fields = forms.CharField(label='主题名')
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols': 80})}

learning_logs_v1/views.py
from django.shortcuts import render,redirect
from .models import Topic,Entry
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# 在这里写视图.
# 主页
def index(request):
    return render(request, 'learning_logs/index.html')


#  显示所有条目的主题
@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    # 生成paginator对象,定义每页显示3条记录
    paginator = Paginator(topics, 3)
    # 从前端获取当前的页码数,默认为1
    page = request.GET.get('page', 1)
    # 把当前的页码数转成整数类型
    currentPage = int(page)
    try:
        print(page)
        topics_list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        topics_list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        topics_list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    context = {'topics_list': topics_list, 'paginator': paginator}

    return render(request, 'learning_logs/topics.html', context)

#  显示单个主题和所有条目的主题
@login_required
def topic_id(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic_id.html', context)

#  添加新主题
@login_required
def new_topic(request):

    if request.method == 'GET':
        # 如果是GET请求，创建一个新表单
        form = TopicForm()
    if request.method == 'POST':
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        # 判断输入的是否有效
        if form.is_valid():
            # commit=False告诉Django先不提交到数据库.
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs_v1:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

# 在特定的主题中添加新的条目
@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    if request.method == 'GET':
        form = EntryForm()
    # 对通过POST提交的表单进行处理
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            # 传递了实参
            new_entries = form.save(commit=False)
            new_entries.topic = topic
            new_entries.save()
            return HttpResponseRedirect(reverse('learning_logs_v1:topic_id', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

# 修改内容
@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            # 传递了参数
            form.save()
            return HttpResponseRedirect(reverse('learning_logs_v1:topic_id',args=[topic.id]))

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

#删除内容
@login_required
def delete_entry(request):
    entry_id = request.GET.get('id')
    Entry.objects.filter(id=entry_id).delete()
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm

# 退出函数
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

# 注册函数
def register(request):
    if request.method!='POST':
        # 显示空的表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        # 验证输入表单的数据是否合法
        if form.is_valid():
            new_user = form.save()
            #  让用户自动登陆，再重定向到主页
            authenticate_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs_v1:index'))

    context={'form':form}
    return render(request,'users/register.html',context)

learning_logs_v1/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>继承模板</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <!-- Static navbar -->
    <nav class="navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapse"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="narbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs_v1:index' %}">Learning log</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs_v1:topics' %}">主题</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello,{{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">注销</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">注册</a></li>
                        <li><a href="{% url 'users:login' %}">登陆</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div>

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div><!-- /container -->
</body>
</html>

learning_logs_v1/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改内容</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'learning_logs_v1:topic_id' topic.id %}">{{ topic.id }}.{{ topic }}</a></p>
<p>编辑内容</p>
    <form action="{% url 'learning_logs_v1:edit_entry' entry.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">edit_entry</button>
    </form>

{% endblock content %}
</body>
</html>

learning_logs_v1/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学习笔记</title>
</head>
<body>
{% extends "learning_logs/base.html"%}
{%block header%}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册一个用户</a> to make your own Learning Log,
        and list the topics you're learing about.
    </h2>
    <h2>
        Whenever you learn something new about a topic,make an entry summarizing what you're learned.
    </h2>
<p><font size="6">学习日志</font></p>
<font size="5">学习，是指通过阅读、听讲、思考、研究、实践等途径获得知识或技能的过程。学习分为狭义与广义两种：
狭义：通过阅读、听讲、研究、观察、理解、探索、实验、实践等手段获得知识或技能的过程，是一种使个体可以得到持续变化（知识和技能，方法与过程，情感与价值的改善和升华）的行为方式。例如通过学校教育获得知识的过程。
    广义：是人在生活过程中，通过获得经验而产生的行为或行为潜能的相对持久的行为方式。</font>
{%endblock content%}
</body>
</html>

learning_logs_v1/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加内容</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>添加新的内容</h2>
{% endblock header %}
{% block content %}
    <p><a href="{% url 'learning_logs_v1:topic_id' topic.id %}">{{ topic.id }}.{{ topic }}</a></p>

    <form action="{% url 'learning_logs_v1:new_entry' topic.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

</body>
</html>

learning_logs_v1/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加主题</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Add a new topic</h2>
{% endblock header %}
{% block content %}

    <form action="{% url 'learning_logs_v1:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>
{% endblock content %}
</body>
</html>

learning_logs_v1/templates/learning_logs/topic_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主题列表</title>
</head>
{%extends "learning_logs/base.html"%}
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs_v1:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
        {% for entries in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>
                        {{ entries.date_added|date:'M d,Y H:i' }}
                        <small>
                            <a href="{% url 'learning_logs_v1:edit_entry' entries.id %}"><button>修改</button></a>
                            <a href="/delete_entry/?id={{ entries.id }}"><button>删除</button></a>
                        </small>
                    </h3>
                </div>
            </div>
            <div class="panel-body">
                <font size="5">{{ entries.text|linebreaks }}</font>
            </div>
        {% empty %}
        <li> 即将添加主题内容。。。</li>
        {% endfor %}
    </ul>
{% endblock content %}
</body>
</html>

learning_logs_v1/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主题</title>
</head>
{%extends "learning_logs/base.html"%}
{% load bootstrap3 %}
{% block header %}
    <h1>学习主题</h1>
{% endblock header %}
{% block content %}
    <ul>
        {% for topics in topics_list %}
        <li>
            <h3>
                <a href="{% url 'learning_logs_v1:topic_id' topics.id %}">{{ topics }}</a>
            </h3>
        </li>
        {% empty %}
        <li> 即将添加主题。</li>
        {% endfor %}
    </ul>
    <ul class="pagination" id="pager">
        {#上一页按钮开始#}
        {# 如果当前页有上一页#}
        {% if topics_list.has_previous %}
            {#  当前页的上一页按钮正常使用#}
            <li class="previous"><a href="/topics/?page={{ topics_list.previous_page_number }}">上一页</a></li>
        {% else %}
            {# 当前页的不存在上一页时,上一页的按钮不可用#}
            <li class="previous disabled"><a href="#">上一页</a></li>
        {% endif %}
        {#上一页按钮结束#}
        {# 页码开始#}
        {% for num in paginator.page_range %}

            {% if num == currentPage %}
                <li class="item active"><a href="/topics/?page={{ num }}">{{ num }}</a></li>
            {% else %}
                <li class="item"><a href="/topics/?page={{ num }}">{{ num }}</a></li>

            {% endif %}
        {% endfor %}
        {# 页码结束 #}
        {# 下一页按钮开始 #}
        {% if topics_list.has_next %}
            <li class="next"><a href="/topics/?page={{ topics_list.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页按钮结束#}
    </ul>
</div>

    <h3>
        <a href ="{% url 'learning_logs_v1:new_topic' %}">Add a new topic:</a>
    </h3>
{% endblock content %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs_v1:index' %}"/>
    </form>
{% endblock content %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs_v1:index' %}"/>
    </form>
{% endblock %}

</body>
</html>